/**
 * Skull Demo
 * Best demo eva
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: skull@skull.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChickenDTO } from './chickenDTO';


export interface ShopDTO { 
    shopName?: string;
    chickenDTOS?: Array<ChickenDTO>;
}

