server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chicken
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  data:
    rest:
      detection-strategy: visibility

security:
  jwtExpirationInSeconds: 28800
